### ISSUE TITLE
Data type table could use smaller fixes

### ISSUE THREAD

**Issue by seberg** [rougier/from-python-to-numpy#11]
I think the data type table at the very end can use some smaller fixes, at least if it refers to how numpy sees types. Things like `int` being seen as `long` and thus not `i4` but maybe `l`, and I like mentioning `intp` as the correct "indexing/size" type independend of platform. (I think this may just be an older version of https://docs.scipy.org/doc/numpy/user/basics.types.html#array-types-and-conversions-between-types)

just for your consideration :).

**Comment by rougier** [comment]
Thanks, didn't know about the intp type. Could make a PR ?
