### ISSUE TITLE
Chapter 4.2: Uniform vectorization - NameError: name 'shape' is not defined

### ISSUE THREAD

**Issue by sc0v0ne** [rougier/from-python-to-numpy#114]
Good morning I'm studied [From Python to Numpy](https://www.labri.fr/perso/nrougier/from-python-to-numpy/#id3). I was testing to the codes as I read. I ended up finding a mistake.

Error:
![image](https://github.com/rougier/from-python-to-numpy/assets/56802572/88e0b71a-3fa5-4eb6-bf62-e73b87d15e00)

I solve the error by adding shape, I don't know if it follows the correct logic following the book. If it's wrong, please correct me.

Solution:
![image](https://github.com/rougier/from-python-to-numpy/assets/56802572/ca7f43e9-6443-4e50-b863-46c44ec9c74c)

Thanks for your attention have great day.

**Comment by rougier** [comment]
Thanks for the report. I'm not sure which part of the book you extract the code but if Z is a numpy array, I should have wrote Z.shape instead of shape. Else (Z is a list of list), your solution looks good. Can you make a PR?

**Comment by sc0v0ne** [comment]
Yes, I can.

**Comment by sc0v0ne** [comment]
I can see that the code is updated, but it is not on the website. Can I update the website? or would this be an admin execution of github actions ?

![image](https://github.com/rougier/from-python-to-numpy/assets/56802572/a8b1cbae-05df-4dcd-9147-6b032dccd98d)

- [04-code-vectorization.rst](https://github.com/rougier/from-python-to-numpy/blob/master/04-code-vectorization.rst)

**Comment by sc0v0ne** [comment]
#115  It has already been resolved, I looked at the history. Just the website itself, which still has old code.

**Comment by rougier** [comment]
I4ve just updated the website.

**Comment by sc0v0ne** [comment]
@rougier Thanks.
