### ISSUE TITLE
Plots for Bellman-Ford example is missing...?

### ISSUE THREAD

**Issue by mdboom** [rougier/from-python-to-numpy#13]
There are some links to .pdf files that seem to be broken:

![image](https://cloud.githubusercontent.com/assets/38294/21437219/96a12fd8-c850-11e6-9b39-3ed005f38156.png)

**Comment by rougier** [comment]
Weird, they are here: 

https://github.com/rougier/from-python-to-numpy/blob/master/data/value-iteration-1.pdf
https://github.com/rougier/from-python-to-numpy/blob/master/data/value-iteration-2.pdf
...
https://github.com/rougier/from-python-to-numpy/blob/master/data/value-iteration-10.pdf

Are you reading from github or from the website ?

**Comment by mdboom** [comment]
Both the website and my local git checkout have the same issue.

I think the problem may be that using an `<img src="...">` to a PDF file simply doesn't work in a web browser.  (So, sorry, I was wrong about them "missing").

**Comment by rougier** [comment]
Fixed.
