### ISSUE TITLE
Missing Highlight CSS ?

### ISSUE THREAD

**Issue by Carreau** [rougier/from-python-to-numpy#16]
You pre block seem to have the correct classes, though do not seem to be highlighted. 

I'm going to __guess__ that this is dues to some path issue as it tries to include some css at weird paths:

`<link rel="stylesheet" href="/usr/locaL/lib/python2.7/site-packages/docutils/writers/html4css1/math.css" type="text/css" />
`
No highlighting on purpose is also a valid answer.

**Comment by rougier** [comment]
Yes, I defined (temporarily) the preblock style to be mostly black with only some bold font until I define a good one. But the linked stylesheet is an error, I need to correct it.

**Comment by rougier** [comment]
Just fixed the math.css inclusion.
