### ISSUE TITLE
More syntax highlightning in code?

### ISSUE THREAD

**Issue by deeplook** [rougier/from-python-to-numpy#19]
Would it be possible to get more syntax highlightning than only making function names bold? There is `pygments` and all that stuff. Maybe this is useful: https://oneau.wordpress.com/2010/05/24/documenting-python-code-with-rest-docutils-pygments-cog-and-paver/

And then, of course, there is Sphinx, but you must have a reason for not using it (?).

**Comment by rougier** [comment]
I'm not a big fan of syntax highlighting actually. rst2html.py is using pygment for syntax highligthing but I did not found a proper theme to go with the website. Any suggestions ? (I'm looking for something with rather subtle colors).
