### ISSUE TITLE
Maybe use ReST include directives

### ISSUE THREAD

**Issue by deeplook** [rougier/from-python-to-numpy#23]
... if there's no policy of having _everything_ in the ReST files. If not, `include`s would minimise the risk of code files and doc files being out of sync. And the ReST `include` directive has many options to pick only what you want, if you don't want to shoe the entire file. In the simplest case an include looks like this:

```rest
.. include:: code/anatomy.py
    :code: python
```

See http://docutils.sourceforge.net/docs/ref/rst/directives.html#including-an-external-document-fragment

**Comment by rougier** [comment]
I agree this is problematic, but it would need more work to split source code properly and get rid of copyright headers, some comments, etc.
