### ISSUE TITLE
Typo in Section 3.2 Memory Layout - len(shape)

### ISSUE THREAD

**Issue by navneethc** [rougier/from-python-to-numpy#24]
Section 3.2, Third paragraph:
> Here, we know that Z itemsize is 2 bytes (int16), the shape is (3,3) and the number of dimensions is 2 (len(shape)).

I believe the command should be `len(Z.shape)`. Of course, to correspond with the code sample which comes immediately after, you could instead have `Z.ndim`.

**Comment by rougier** [comment]
You're right, it's Z.shape and for the ndim, the goal was also to explain that len(Z.shape) = Z.ndim
