### ISSUE TITLE
colloquial #1

### ISSUE THREAD

**Issue by mortadelle07** [rougier/from-python-to-numpy#27]
Change:
"""
If you don't comment your code at the time of writing, **you'll be unable to guess** what a function is doing after a **few weeks (or even days)**
"""
To:
"""
If you don't comment your code at the time of writing, **you won't be able to tell** what a function is doing after a **few days (or even weeks)**
"""

**Comment by rougier** [comment]
Thanks. Why did you reverse day and weeks ? My idea was to point out that most probably this will be forgotten in a few weeks but in some case, even after a few days (much shorter period), this will be also forgotten.

**Comment by mortadelle07** [comment]
My mistake: I should have removed the word "even". The point you're making is that the reader is going to be confused with what she coded after a short period of time, so it's better to state that way "in days" but to grant the reader who may think your timetable is too aggressive in softening your stance "in weeks".  Therefore "after a few days (or weeks)" carries your point.
I believe your use of "even" (in your original writing) comes from your translation of something like "apres quelques semaines (voire meme quelques jours)". Here the "meme" says that "in days" are possible. "Even" does not say quite like that.
If you want to keep something close to your original writing, I think that "after a few weeks (or possibly days)" would be better.

**Comment by rougier** [comment]
Thanks for the explanation. And you're totally right in your analysis of my French thinking. I'll use your proposal
```
If you don't comment your code at the time of writing, you won't be
able to tell what a function is doing after a few weeks (or possibly days).
```

Or can you make a PR  (such that your name appears as a contributor) ?

Happy new year.

**Comment by rougier** [comment]
It's been corrected.
