### ISSUE TITLE
colloquial #2

### ISSUE THREAD

**Issue by mortadelle07** [rougier/from-python-to-numpy#28]
Consider changing:
"""
What would be the best way? The syntax below is rather obvious (at least for who is familiar with numpy) but the question is to known whether this is the fastest way.
"""
To:
"""
How does one write it to maximize speed? The below syntax is rather obvious (at least for those familiar with numpy) but the above question asks to find the fastest operation.
"""

**Comment by rougier** [comment]
Thanks. Could you make a PR ?

**Comment by rougier** [comment]
It's been corrected.
