### ISSUE TITLE
Grammar corrections in Section 4.1

### ISSUE THREAD

**Issue by vijaykartik** [rougier/from-python-to-numpy#34]
Section 4.1 Introduction

1. In the second sentence: The phrase

"Of course it does not mean it is easy **nor** straightforward, but at least it does not necessitate **to** totally **rethink** your problem..."

would be replaced by

"Of course it does not mean it is easy **or** straightforward, but at least it does not necessitate totally **rethinking** your problem..."

2. In the fourth sentence: "most simple" should be "simplest". My personal preference here would be to replace "the simplest example" by "a simple example", but then it is no longer a suggested correction!

**Comment by rougier** [comment]
Thanks, I've corrected.
