### ISSUE TITLE
Incorrect Python version

### ISSUE THREAD

**Issue by reidfaiv** [rougier/from-python-to-numpy#39]
Section 1.2 declares Python version 3.5.2 however section 2.1 "vectorized approach" uses random.choices() function which was introduced in Python 3.6.

https://docs.python.org/3.6/library/random.html#random.choices

**Comment by rougier** [comment]
It has been introduced with issue #37. Previous version was `steps = random.sample((-1, +1)*n, n)`
I'll revert to previous version. According to Python documentation it is equivalent to a shuffle.

**Comment by rougier** [comment]
Done.
