### ISSUE TITLE
Typos in 7.3

### ISSUE THREAD

**Issue by SeanDS** [rougier/from-python-to-numpy#44]
Excellent work!

I noticed two minor grammatical issues in section 7.3, "Scipy & co" (file `07-beyond-numpy.rst`):

- "there is a trillion" -> "there are a trillion"
- "it was not the goal" -> "that was not the goal"

**Comment by rougier** [comment]
Thank you! Could you make a PR ?

**Comment by SeanDS** [comment]
Ok, there you go. The reason I opened an issue is because the instructions in `How to contribute` point me here, so I figured you wanted issues created instead of pull requests. You might want to make the instructions clearer.

**Comment by rougier** [comment]
Thanks, will do.
