### ISSUE TITLE
Typos 3.3

### ISSUE THREAD

**Issue by pylang** [rougier/from-python-to-numpy#48]
> Thus, if you need fancy indexing, it's better to keep a copy of **your** fancy index (especially if it was complex to compute it) and to work with it:

...

> If you are unsure if the result of **your** indexing is a view or a copy, you can check what is the base of your result. If it is None, then you result is a copy:

...

> However, if your arrays are big, then you have to be careful with such **expressions** and wonder if you can do it differently

**Comment by rougier** [comment]
Thansk ! It has been corrected.
