### ISSUE TITLE
Horizontal scroll appears

### ISSUE THREAD

**Issue by Gebon** [rougier/from-python-to-numpy#52]
On my laptop's screen (viewport is 1304x702) the book have a horizontal scroll. Do anyone else have this issue?
![Horizontal scroll issue](http://savepic.ru/12857222.png)

**Comment by Gebon** [comment]
I've tested with browsershots.org. It's not only my issue. The scroll appears because of the `.note` and `.legend` DOM-elements

**Comment by rougier** [comment]
Yes, the HTML template needs to be more responsive this would require some work.
