### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by stared** [rougier/from-python-to-numpy#57]
Right now http://www.labri.fr/perso/nrougier/from-python-to-numpy/ does not respond.

**Comment by rougier** [comment]
Sorry, I saw you message quite late. It's working for me.

Also, you can try:
http://downforeveryoneorjustme.com/http://www.labri.fr/perso/nrougier/from-python-to-numpy

**Comment by stared** [comment]
Now it's up. :)
Thx for link, sorry for raising a (possibly false) alarm.

(I am writing deep learning intro and wanted to make sure sources I recommend are up.)
