### ISSUE TITLE
Syntax error on 3.3

### ISSUE THREAD

**Issue by ssantic** [rougier/from-python-to-numpy#60]
In section 3.1, in the example on using .base for checking whether an object is a view or a copy of the original, there is a syntax error:

`Z = np.random.uniform(0,1,(5,,5))`

This isn't present in the repository, but for some reason is still present in the text on the book website.

**Comment by rougier** [comment]
Thanks. Most probably I didn't update the html build.

**Comment by rougier** [comment]
Should be corrected by now.
