### ISSUE TITLE
meshgrid is not explained - very important for 3D plots and algorithms

### ISSUE THREAD

**Issue by denfromufa** [rougier/from-python-to-numpy#65]
2 of your exercises use this function:

http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

**Comment by rougier** [comment]
Can you give somemore details ?

**Comment by denfromufa** [comment]
There is one example for contour plot in numpy docs:

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.meshgrid.html#numpy.meshgrid

**Comment by rougier** [comment]
Thanks. My question was rather what was your solution to include `meshgrid` in the book. Do you think there some section where it would fit? (Note I did not include everything in the book).

**Comment by makmanalp** [comment]
Also handy for parametric plots!

**Comment by denfromufa** [comment]
I think somewhere between reshaping and broadcasting would be a good fit:

http://www.labri.fr/perso/nrougier/from-python-to-numpy/#reshaping

**Comment by makmanalp** [comment]
Or perhaps `creation`? In my mind it's a bit like `diag` or `triu` in that you give it some numbers to create more complex matrices.

**Comment by rougier** [comment]
Does anyone want to propose a PR ?
