### ISSUE TITLE
Confusing "if 0" statement

### ISSUE THREAD

**Issue by Motor-taxi-master-rider** [rougier/from-python-to-numpy#71]
https://github.com/rougier/from-python-to-numpy/blob/1946c83e6f2b466688239adaa63c9c60d5aa6379/code/boid_numpy.py#L194

This line of script made me confusing. Does "if 0" means below block of code will never be executed?

**Comment by rougier** [comment]
Exactly. It's a very cheap "option". If you replace 0 with 1, you'll see the code executed.

**Comment by Motor-taxi-master-rider** [comment]
Thanks for your kind explanation.
