### ISSUE TITLE
`from tools import timeit`? (chapter 2 ghost tools library)

### ISSUE THREAD

**Issue by SebastianoF** [rougier/from-python-to-numpy#84]
In chapter 2, should `from tools import timeit` be `from timeit import timeit`?
I could not find a tools folder in the repo or a tools library.

Thanks

**Comment by ashwinvis** [comment]
There is one: https://github.com/rougier/from-python-to-numpy/blob/master/code/tools.py

**Comment by SebastianoF** [comment]
Awesome, thanks!!
...I had totally missed it!
