### ISSUE TITLE
mention einsum

### ISSUE THREAD

**Issue by TejasAvinashShetty** [rougier/from-python-to-numpy#88]
Dear Dr Nicolas P. Rougier,
      
I think it would be great if you could mention einsum, tensordot, kron and other powerful but less used numpy functions

**Comment by rougier** [comment]
Dear Tejas, 

I agree this could be mentioned but the book is voluntarily limited and do no address everything. This is also the reason for the bibliography and the reference to the numpy 100 exercises.

**Comment by TejasAvinashShetty** [comment]
Thank you for your reply. Are there any numpy for physicists books?

**Comment by rougier** [comment]
I don't know any but they might exist nonetheless. You can ask on numpy mailing list, maybe someone knows the answer.

**Comment by TejasAvinashShetty** [comment]
:thinking:  Thank you, Dr Rougier
